Update test instructions in README
Trying to run `src/functions.py` directly causes:

```
[15:17:52] zoni in ~/Workspace/zoni/ulauncher-snippets on main
➔  python3 src/functions.py
Traceback (most recent call last):
  File "/home/zoni/Workspace/zoni/ulauncher-snippets/src/functions.py", line 23, in <module>
    from .filters import camelcase, pascalcase, kebabcase, snakecase
ImportError: attempted relative import with no known parent package
```

This is solved by invoking the module via `-m`.

Alternatively the relative import could be adjusted, but this feels
safer.